spring:
  session:
    store-type: none
  jackson:
    serialization:
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#ribbon超时设置
#ReadTimeout 设置路由转发请求的时候，创建请求连接的超时时间
#ConnectTimeout 用来设置路由转发请求的超时时间
ribbon:
  ReadTimeout: 11000
  ConnectTimeout: 11000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

# test
service-exchange-vip-api:
  ribbon:
    ReadTimeout: 16000
    ConnectTimeout: 16000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
bitrade-market:
  ribbon:
    ReadTimeout: 6000
    ConnectTimeout: 6000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true

#hystrix超时配置
#设置API网关中路由转发请求的HystrixCommand执行超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    service-exchange-vip-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
    bitrade-market:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

### zuul.routes 网管api配置
#禁用一个 zuul.<SimpleClassName>.<filterType> .disable = true
zuul:
  routes:
    exchange-vpi:
      serviceId: service-exchange-vip-api
      path: /exchange-vip/**
      stripPrefix: false
      customSensitiveHeaders: true
    market:
      serviceId: bitrade-market
      path: /market/**
      stripPrefix: false
      customSensitiveHeaders: true
